language: python

python:
  - "3.7"

services:
  - docker

install:
  - bash deploy.sh sartography/cr-connect-python-base

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
