language: python

python:
  - "3.7"

services:
  - docker

install:
  - sudo pip install --upgrade pip
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(dev|testing|demo|training|staging|master|rrt\/.*)$

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
