language: python

python:
  - "3.7"

services:
  - docker

install:
  - sudo pip install --upgrade pip
  - export PATH=$PATH:$HOME/.local/bin

script:
  - bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
